spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/ai_travel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    # username: root
    # password: lx6144031
    # driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://ai-travel-mysql:3306/ai_travel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver  

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ai.aitravelplanner.entity
  configuration:
    map-underscore-to-camel-case: true

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: {your_key}
      model-name: qwen-flash
amap:
  key: {your_key}


server:
  port: 8081
